apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-app
  labels:
    app: jwt-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jwt-app
  template:
    metadata:
      labels:
        app: jwt-app
    spec:
      containers:
      - name: netflix-app
        image: vicky275/jwtbasic:v07
        ports:
        - containerPort: 3000
